"""
report_engine/markdown_reporter.py - Markdown report generation (human-friendly)
"""
from pathlib import Path
from datetime import datetime
from typing import Optional

from ..checklist_engine.models import ChecklistAnalysisReport, ItemStatus
from ..utils.logger import get_logger

logger = get_logger(__name__)


def generate_markdown_report(
    report: ChecklistAnalysisReport, 
    output_dir: Path = None
) -> Path:
    """
    Generate human-friendly Markdown report.
    
    Args:
        report: ChecklistAnalysisReport object
        output_dir: Directory to save report (default: output/reports/)
        
    Returns:
        Path to generated Markdown file
    """
    if output_dir is None:
        output_dir = Path("output/reports")
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_file = output_dir / f"{report.report_id}_{timestamp}.md"
    
    # Build markdown content
    content = _build_markdown(report)
    
    # Write file
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(content)
    
    logger.info("markdown_report_generated", file=str(output_file))
    return output_file


def _build_markdown(report: ChecklistAnalysisReport) -> str:
    """Build complete markdown document"""
    
    stats = report.stats_summary()
    
    md = []
    
    # Header
    md.append("# PRISMA 2020 Scoping Review Checklist Analysis")
    md.append("")
    md.append(f"**Document:** {report.document_filename}")
    md.append(f"**Pages:** {report.document_total_pages}")
    md.append(f"**Analysis Date:** {report.generated_at.strftime('%Y-%m-%d %H:%M:%S')}")
    md.append(f"**LLM Model:** {report.llm_model}")
    md.append(f"**Extraction Quality:** {report.extraction_quality}")
    md.append("")
    
    # Executive Summary
    md.append("## 📊 Executive Summary")
    md.append("")
    md.append(f"- **Total Items Analyzed:** {stats['total_items_analyzed']}")
    md.append(f"- **Items Applicable:** {stats['items_applicable']}")
    md.append(f"- **Average Confidence:** {stats['average_confidence']:.1%}")
    md.append("")
    
    # Status breakdown as visual grid
    md.append("### Status Breakdown")
    md.append("")
    
    status_counts = stats.get("status_breakdown", {})
    for status in ["presente", "parziale", "assente", "non_applicabile", "incerto"]:
        count = status_counts.get(status, 0)
        total = stats["total_items_analyzed"]
        if total > 0:
            percentage = (count / total) * 100
            bar_length = int(percentage / 5)  # Max 20 chars
            bar = "█" * bar_length + "░" * (20 - bar_length)
            md.append(f"**{status.upper()}** `{bar}` {count}/{total} ({percentage:.0f}%)")
    
    md.append("")
    
    # Assumptions
    md.append("## ℹ️ Methodological Notes")
    md.append("")
    md.append("### Assumptions Made")
    for assumption in report.assumptions_made:
        md.append(f"- {assumption}")
    md.append("")
    
    md.append("### Limitations and Caveats")
    for limitation in report.limitations_noted:
        md.append(f"- {limitation}")
    md.append("")
    
    # Detailed Item Results
    md.append("## 📋 Detailed Item Assessments")
    md.append("")
    
    for i, result in enumerate(report.analysis_results, 1):
        md.append(_format_item_result(result, i))
        md.append("")
    
    # Recommendations
    md.append("## 💡 Recommendations for Improvement")
    md.append("")
    
    items_to_improve = [
        r for r in report.analysis_results 
        if r.status in ["assente", "parziale", "incerto"]
    ]
    
    if items_to_improve:
        for result in items_to_improve:
            if result.improvement_suggestions:
                md.append(f"### {result.item_id}. {result.item_title}")
                md.append(f"**Current Status:** {result.status}")
                md.append(f"**Suggestion:** {result.improvement_suggestions}")
                md.append("")
    else:
        md.append("All items are either well-documented (presente) or marked as non-applicable.")
        md.append("")
    
    # Footer
    md.append("---")
    md.append(f"*Report generated by PRISMA Analyzer MVP (v0.1)*")
    md.append(f"*This report is based on LLM analysis and should be reviewed by domain experts.*")
    
    return "\n".join(md)


def _format_item_result(result, item_number: int) -> str:
    """Format a single item result as markdown"""
    
    md = []
    
    # Item header with status badge
    status_emoji = {
        "presente": "✅",
        "parziale": "⚠️",
        "assente": "❌",
        "non_applicabile": "⊘",
        "incerto": "❓"
    }
    
    emoji = status_emoji.get(result.status, "")
    md.append(f"### {emoji} Item {result.item_id}: {result.item_title}")
    md.append("")
    
    # Status and confidence
    md.append(
        f"**Status:** `{result.status}` | "
        f"**Confidence:** {result.confidence:.0%} | "
        f"**Applicable:** {'Yes' if result.is_applicable else 'No'}"
    )
    md.append("")
    
    # Motivation
    md.append("**Assessment:**")
    md.append(result.motivation)
    md.append("")
    
    # Evidence
    if result.evidence_items:
        md.append("**Evidence Found:**")
        md.append("")
        for i, evidence in enumerate(result.evidence_items, 1):
            md.append(f"{i}. **Quote:** _{evidence.text_excerpt}_")
            md.append(f"   - **Page:** {evidence.page_number or 'N/A'}")
            md.append(f"   - **Type:** {evidence.evidence_type} (confidence: {evidence.confidence:.0%})")
            md.append(f"   - **Note:** {evidence.explanation}")
            md.append("")
    else:
        md.append("*No specific evidence extracted.*")
        md.append("")
    
    # Additional notes
    if result.professional_note:
        md.append("**Professional Note:**")
        md.append(result.professional_note)
        md.append("")
    
    # Suggestions for improvement
    if result.improvement_suggestions:
        md.append("**Suggestion for Improvement:**")
        md.append(result.improvement_suggestions)
        md.append("")
    
    return "\n".join(md)
